name: Web API build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build SandboxApi --configuration Release
    - name: dotnet publish
      run: dotnet publish SandboxApi -c Release -o webapi_deploy
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v1
      with:
        app-name: fiddlersandboxapi
        publish-profile: ${{ secrets.API_PUBLISH_PROFILE }}
        package: 'SandboxApi/webapi_deploy'