name: .NET Core Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish
      run: dotnet publish -c Release -o deploy 
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v1
      with:
        app-name: fiddlersandbox
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: 'SandboxWebApp/deploy'
